=== XQuarks/gamesdk/test/memoryadvice/memoryadvice_common/src/main/resources/schemas/launchParams.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "title": "Launch Parameters",
  "description": "Configuration for a test run.",
  "additionalProperties": false,
  "properties": {
    "tests": {
      "$ref": "testArray.schema.json"
    },
    "coordinates": {
      "type": "array",
      "items": {
        "type": "integer",
        "minimum": 0,
        "maximum": 100
      }
    },
    "run": {
      "type": "string"
    },
    "started": {
      "$ref": "time.schema.json"
    }
  },
  "type": "object"
}

=== XQuarks/gamesdk/test/istresser/app/src/main/assets/default.json
{
  "tests": [
    [
      {},
      {
        "malloc": 40
      }
    ],
    [
      {},
      {
        "blocker": true
      }
    ],
    [
      {},
      {
        "heuristics": [
          "TRIM"
        ]
      },
      {
        "heuristics": [
          "LOW"
        ]
      },
      {
        "heuristics": [
          "CL"
        ]
      }
    ]
  ],
  "coordinates": [
    1,
    0,
    1
  ],
  "run": "43a57d56-7fc1-49f1-89fc-9da39bb5be91",
  "started": 1581508211344
}
